"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Link from "next/link";




const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { name: "MOVIES", href: "/" ? "/movies" : "" },
  { name: "TV SHOWS", href: "/tvshows" },
];

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex text-center bg-gray-900 space-x-8 py-4">
          <h1 className="text-red-600 ml-2 font-serif text-2xl">StreamFilm</h1>
          <ul className="flex space-x-5 text-white px-8">
            {links.map((link) => {
              const isActive = pathname === link.href;
              return (
                <li key={link.name} className="relative">
                  <Link href={link.href} className={isActive ? " border-b-4 border-red-500" : ""}>
                    {link.name}
                  </Link>
                </li>
              );
            })}
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
