"use client";
import Link from "next/link";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { name: "Movies", href: "/" },
  { name: "TV Shows", href: "/tvshows" },
];

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center bg-neutral-900 text-white py-6 space-x-20">
          <h1 className="text-red-600 text-xl font-bold">StreamFilm</h1>
          <ul className="flex space-x-6">
            {links.map((link) => {
              const isActive = pathname === link.href;
              return (
                <li key={link.name} className={isActive ? "border-b-4 border-red-600" : ""}>
                  <Link href={link.href}>
                    {link.name}
                  </Link>
                </li>
              );
            })}
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
