export const metadata = {
    title: 'movies',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
    return (
      <>
      {children}
      </>
         
    );
  }